const express = require('express');
const router = express.Router();
const {SignUp,fetchSignup,login,createOrder,getAllData,pendingdata,getAllPendingData,deletedata,SendEmail,UpdateOtp,TaskComplete,contactmail,createmoney,updatemoney,getmoney} = require('./Controller');
router.post("/signup",SignUp);
router.post("/login",login);
router.post("/createorder",createOrder);
router.post("/getdata",getAllData);
router.post("/pendingdata",pendingdata);
router.post("/getpendingdata",getAllPendingData);
router.post("/deletedata",deletedata);
router.post("/sendmail",SendEmail);
router.post("/updateotp",UpdateOtp);
router.post("/taskcomp",TaskComplete);
router.post("/contactmail",contactmail);
router.post("/createmoney",createmoney);
router.post("/updatemoney",updatemoney);
router.post("/getmoney",getmoney);
router.post("/findusername",fetchSignup);
module.exports = router;